apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enduro-sdps
resources:
  - prometheus.yaml
  - grafana-alloy.yaml
  - grafana-tempo.yaml
  - grafana.yaml
patches:
  - target:
      kind: Deployment
      name: enduro
    path: enduro-telemetry-patch.yaml
  - target:
      kind: StatefulSet
      name: enduro-a3m
    path: enduro-a3m-telemetry-patch.yaml
  - target:
      kind: Deployment
      name: enduro-am
    path: enduro-am-telemetry-patch.yaml
