apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enduro-sdps
resources:
  - enduro-dashboard.yaml
  - enduro.yaml
  - minio-setup-buckets-job.yaml
  - minio.yaml
  - mysql.yaml
  - namespace.yaml
  - redis.yaml
  - role.yaml
  - role-binding.yaml
  - service-account.yaml
  - temporal-ui.yaml
  - temporal.yaml
